[package]
name = "lab5"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "22.0"
winit = "0.30"
bytemuck = { version = "1.14", features = ["derive"] }
pollster = "0.3"
env_logger = "0.11"
nalgebra = "0.33"  # tu versi√≥n actual